version: '2'
services:
    controlepatrimonial-app:
        image: controlepatrimonial
        external_links:
            - controlepatrimonial-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/ControlePatrimonial
        ports:
            - 8080:8080
    controlepatrimonial-postgresql:
        extends:
            file: postgresql.yml
            service: controlepatrimonial-postgresql
